/**

By Mohammad Mayyan, August 1st, 2022
This code reads three files:
  1- XX.smartTable    contains raw data generated by the smart dining table.
                      The table is assumed to have nothing placed on it during
                      the first 5 seconds. This period is used for computing the
                      tare values.
  2- XX.calibration   contains calibration values for the grid of load cells to
                      convert raw data into weights in grams
  3- XX.groundTruth   contains manually labeled ground truth for the moments at
                      which bites of food and beverage were put in mouth.
The code segments each image of weights into food containers (plate, cup, and
bowl), detects bites consumed from each food container, then evaluates the
detections against the ground truth moments.


Compilation:
make

Usage:
./smartDiningTable XXX.smartTable



*/

#include "smartDiningTable.h"



int main(int argc, char const *argv[])
{
  if(argc < 2)
  {
    printf("Usage: ./smartDiningTable data.smartTable \n");
  }
  loadFiles(argv);

  processSegmentationAndBiteDetection();

  if (groundTruthLoaded)
  {
    printf("\n\tF1Score for consumed bites\n");
    computeF1Score_Hoover(
      detectedWeights,
      true,	// consumed = 1, picked up = 0
      false,										// yes = 1, no = 0
      true										// yes = 1, no = 0
    );

  }

  return 0;
} // main
